### ISSUE TITLE
改变很慢

### ISSUE THREAD

**Issue by pingcoder0505** [welcommand/WELCustomStatusbarColor#2]
为什么我在真机上改变颜色会改变的很慢?而且中国移动什么的改变不了,还有上边其它的一些颜色都改不了?

**Comment by welcommand** [comment]
请问系统是什么版本呢？

**Comment by pingcoder0505** [comment]
ios 10左右的,而且我用在别的项目中没事儿!我怀疑是不是我这个项目中runtime类太多了造成的?

**Comment by welcommand** [comment]
这个和Runtime用的多应该没关系。这个项目变颜色的时候会调用系统自带的更新方法setNeedsStatusBarAppearanceUpdate。可以单纯的调试下这个方法为什么会慢

**Comment by pingcoder0505** [comment]
那这个该怎么解决啊?目前我也是没思路

**Comment by pingcoder0505** [comment]
objc_setAssociatedObject([self class], @"wel_statusbarIconColor", color, OBJC_ASSOCIATION_RETAIN_NONATOMIC);
    [[UIApplication sharedApplication].keyWindow.rootViewController setNeedsStatusBarAppearanceUpdate];    这个方法也调用了!只是不知道为什么会变得那么慢,而且还有不显示的

**Comment by welcommand** [comment]
在wel_imageWithColor下个断点，看看是为啥。。。。

**Comment by pingcoder0505** [comment]
过段时间才会调wel_imageWithColor这个方法,但是调完只会先改个时间!剩下的还是没改!

**Comment by welcommand** [comment]
嗯 ，看看是为什么过了段时间才调用wel_imageWithColor

**Comment by pingcoder0505** [comment]
我也不知道啊!

**Comment by pingcoder0505** [comment]
这跟网络有关吗?怎么偶尔一次就成功了!剩下的都不行!感觉有时候那个方法会一直调,有时候只会调用一次

**Comment by welcommand** [comment]
请试用1.0.2，看看是不是解决了问题:)
